### ISSUE TITLE
Auth işlemi ve teşekkürler

### ISSUE THREAD

**Issue by berkslv** [muratti66/yapikredi_api_notes#1]
Selamlar, vakit ayırıp böyle bir dökümantasyon oluşturduğunuz için teşekkürler. Bankanın sağladığı dökümantasyon çok yetersiz.

Eğer yardımcı olabilirseniz bir soruda sormak istiyorum. Panelden uygulama oluşturduktan sonra access key elde etmek için bankanın bizi doğrulamasını bekliyoruz sanırım. Eğer tecrübe ettiyseniz bu süreç ne kadar sürüyor acaba?

**Comment by muratti66** [comment]
Merhabalar, size faydalı olacağına sevindim
Doğrulama beklenmekte ve bende doğrulamanın tamamlanması 10 gün kadar sürmüştü
